version: '3.1'

services:
  # Web is the "EDGE" node atm, eventually will go behind a HA proxy that
  # sits on the node with the domain we want for web. It will load balance
  # on the internal vip, that way other nodes don't have publiclly exposed
  # ports that they don't need.
  web:
    image: ritsse/onerepo
    environment:
      - 'SITE_ROOT=http://0.0.0.0:80'
    networks:
      - external
    deploy:
     replicas: 2
     labels:
       - "traefik.backend=sse"
       - "traefik.frontend.rule=Host:${HOST}"
       - "traefik.port=80"
       - "traefik.enable=true"
       - "traefik.docker.network=external"
       - "traefik.backend.loadbalancer.sticky=true"
       - "traefik.backend.loadbalancer.swarm=true"

  # API, running on devlop for now
  api_v2:
    image: ritsse/node-api:devlop
    deploy:
      replicas: 4
      labels:
        - "traefik.backend=api_v2"
        - "traefik.frontend.rule=Host:${HOST};PathPrefix:/api/v2"
        - "traefik.port=3000"
        - "traefik.enable=true"
        - "traefik.docker.network=external"
        - "traefik.backend.loadbalancer.swarm=true"
    environment:
      - GOOGLE_CLIENT_ID_FILE=/run/secrets/GOOGLE_CLIENT_ID
      - GOOGLE_CLIENT_SECRET_FILE=/run/secrets/GOOGLE_SECRET
      - GOOGLE_API_KEY_FILE=/run/secrets/GOOGLE_API_KEY
      - MENTOR_GOOGLE_CALENDAR_FILE=/run/secrets/MENTOR_GOOGLE_CALENDAR
      - NODE_ENV=production
      - SLACK_SECRET_FILE=/run/secrets/SLACK_SECRET
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
    secrets:
      - GOOGLE_CLIENT_ID
      - GOOGLE_SECRET
      - SLACK_SECRET
      - GOOGLE_API_KEY
      - MENTOR_GOOGLE_CALENDAR
      - postgres_password
    networks:
      - external
      - internal

  # Just using the production one because A/B testing will be awful
  # will be disabled
  go:
    image: "ritsse/go"
    environment:
      - 'API_ROOT=http://api:3000/api/v2/'
    networks:
      - external
      - internal
    deploy:
      replicas: 0
      labels:
        - "traefik.backend=go"
        - "traefik.frontend.rule=Host:${HOST};Path:/go/{link}"
        - "traefik.port=8000"
        - "traefik.enable=false"
        - "traefik.docker.network=external"
        - "traefik.backend.loadbalancer.swarm=true"

networks:
  external:
    external: true
  internal:
    external: true

# All secrets are external until secrets matures a bit more and services can
# provide them
secrets:
  postgres_password:
    external: true
  GOOGLE_CLIENT_ID:
    external: true
  GOOGLE_SECRET:
    external: true
  GOOGLE_API_KEY:
    external: true
  MENTOR_GOOGLE_CALENDAR:
    external: true
  SLACK_SECRET:
    external: true
