crazy-train:
  build: ./pages/crazy-train
  ports:
    - 127.0.0.1:70:8000
events:
  build: ./pages/events
  ports:
    - 127.0.0.1::8000
go:
  build: ./pages/go
  ports:
    - 127.0.0.1::8000
me:
  build: ./pages/me
  ports:
    - 127.0.0.1::8000
node-api:
  build: ./pages/node-api
  volumes:
    - './example_configs/node_api_keys:/app/keys'
    - './example_configs/node_api_database:/app/config/database/configs'
    - './pages/node-api/:/app/'
  environment:
    - NODE_ENV=development
  ports:
    - 3000:3000
officers:
  build: ./pages/officers
  ports:
    - 127.0.0.1::8000
qdb-3.0:
  build: ./pages/qdb-3.0
  ports:
    - 127.0.0.1::8000
scoreboard-2.0:
  build: ./pages/scoreboard-2.0
  ports:
    - 127.0.0.1::8000

gateway:
  build: ./nginx
  ports:
    - "80:80"
    - "443:443"
  links:
    - crazy-train:ct
    - events
    - go
    - me
    - node-api:api
    - officers
    - qdb-3.0:qdb
    - scoreboard-2.0:scoreboard
