version: '3.1'

services:
  dev_web:
    image: ritsse/onerepo:dev-latest
    networks:
      - external
    deploy:
     replicas: 1
     labels:
       - "traefik.backend=dev_sse"
       - "traefik.frontend.rule=Host:${HOST}"
       - "traefik.port=80"
       - "traefik.enable=true"
       - "traefik.weight=0"
       - "traefik.docker.network=external"
       - "traefik.backend.loadbalancer.sticky=true"
       - "traefik.backend.loadbalancer.swarm=true"
  dev_api_v2:
    image: ritsse/node-api:dev-latest
    deploy:
      replicas: 1
      labels:
        - "traefik.backend=dev_api_v2"
        - "traefik.frontend.rule=Host:${HOST};PathPrefix:/api/v2"
        - "traefik.port=3000"
        - "traefik.enable=true"
        - "traefik.docker.network=external"
        - "traefik.backend.loadbalancer.swarm=true"
      resources:
        limits:
          cpus: '0.25'
          memory: 512M
    environment:
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
      - GOOGLE_CLIENT_ID_FILE=/run/secrets/GOOGLE_CLIENT_ID
      - GOOGLE_CLIENT_SECRET_FILE=/run/secrets/GOOGLE_SECRET
      - MAILGUN_SECRET_FILE=/run/secrets/MAILGUN_SECRET_DEV
      - MAILGUN_DOMAIN_FILE=/run/secrets/MAILGUN_DOMAIN_DEV
      - SLACK_SECRET_FILE=/run/secrets/SLACK_SECRET
      - DB_HOST_OVERRIDE=postgres
      - NODE_ENV=production
    secrets:
      - MAILGUN_SECRET_DEV
      - MAILGUN_DOMAIN_DEV
      - GOOGLE_CLIENT_ID
      - GOOGLE_SECRET
      - SLACK_SECRET
      - postgres_password
    networks:
      - external
      - internal_dev
  dev_go:
    image: "ritsse/go:dev"
    environment:
      - 'API=http://dev_api_v2:3000'
    networks:
      - external
      - internal_dev
    deploy:
      replicas: 1
      labels:
        - "traefik.backend=dev_go"
        - "traefik.frontend.rule=Host:${HOST};Path:/go/{link}"
        - "traefik.port=8000"
        - "traefik.enable=true"
        - "traefik.docker.network=external"
        - "traefik.backend.loadbalancer.swarm=true"
networks:
  external:
    external: true
  internal_dev:
    external: true
# All secrets are external until secrets matures a bit more and services can
# provide them
secrets:
  MAILGUN_SECRET_DEV:
    external: true
  MAILGUN_DOMAIN_DEV:
    external: true
  postgres_password:
    external: true
  GOOGLE_CLIENT_ID:
    external: true
  GOOGLE_SECRET:
    external: true
  SLACK_SECRET:
    external: true
