version: '3.1'

services:
  qmailmanager:
    image: ritsse/qmail
    networks:
      - internal
    volumes:
      - qmail:/qmail

networks:
  internal:
    external: true

volumes:
  qmail:
    external: true
