version: '3.1'

services:
  qmailmanager:
    image: ritsse/qmail
    networks:
      - internal
    volumes:
      - qmail:/qmail

  alms:
    image: ritsse/alms:2.0
    environment:
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
    networks:
      - internal
    secrets:
      - postgres_password

networks:
  internal:
    external: true

secrets:
  postgres_password:
    external: true

volumes:
  qmail:
    external: true
