version: '3.1'

services:
  postgres:
    image: 'postgres:9.6.2'
    environment:
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
    volumes:
      - pgdata:/var/lib/postgresql/data
    deploy:
      mode: global
      placement:
        constraints:
          - node.labels.db == true
    secrets:
      - source: postgres_password
        target: postgres_password
        uid: '999'
        gid: '999'
        mode: 0440
    networks:
      - internal

  redis:
    image: redis:3.2.8
    networks:
      - internal

networks:
  internal:
    external: true

# All secrets are external until secrets matures a bit more and services can
# provide them
secrets:
  postgres_password:
    external: true

volumes:
  # Caddy cache makes it so we don't refetch certs on redeploy
  pgdata:
    external: true
