version: '3.3'

services:
  proxy:
    image: traefik
    configs:
      - source: traefik.toml
        target: /etc/traefik/traefik.toml
    networks:
      - external
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - letsencrypt:/etc/traefik/acme
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: '0.95'
          memory: 512M

configs:
  traefik.toml:
    file: ./traefik.toml

networks:
  external:
    external:
      name: external

volumes:
  letsencrypt:

