defaultEntryPoints = ["http", "https"]

[acme]
email = "tech@sse.rit.edu"
storage = "/etc/traefik/acme/acme.json"
entryPoint = "https"
delayDontCheckDNS = 0
acmeLogging = true
OnHostRule = true

[entryPoints]
    [entryPoints.http]
    address = ":80"
      [entryPoints.http.redirect]
        entryPoint = "https"
    [entryPoints.https]
    address = ":443"
    	[entryPoints.https.tls]

[web]
address = ":8080"
ReadOnly = true

[web.statistics]
  RecentErrors = 10

[web.metrics.prometheus]
  Buckets=[0.1,0.3,1.2,5.0]

[web.auth.digest]
  users = ["admin:traefik:32ef3a792ad16b7a91845be410b386c1"]

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "docker.localhost"
watch = true
exposedbydefault = false
swarmmode = true
