version: "3.1"

services:
  gateway:
    ports:
      - 8081:80
    command: '--conf /etc/Caddyfile --email tech@sse.rit.edu'
    image: 'ritsse/gateway:notls'
    networks:
      - external
      - old
  ct:
    image: 'ritsse/crazy-train:latest'
    networks:
      - old
  events:
    image: 'ritsse/events:latest'
    networks:
      - old
  go:
    environment:
      - 'API_ROOT=http://api:3000/api/v1/'
    image: 'ritsse/go:latest'
    networks:
      - old
  officers:
    image: 'ritsse/officers:latest'
    networks:
      - old
  qdb:
    image: 'ritsse/qdb-3.0:latest'
    networks:
      - old
  scoreboard:
    image: 'ritsse/scoreboard-2.0:latest'
    networks:
      - old


  api:
    image: ritsse/node-api
    deploy:
      replicas: 1
      labels:
        - "traefik.backend=api_v1"
        - "traefik.frontend.rule=Host:${HOST};PathPrefix:/api/v1"
        - "traefik.port=3000"
        - "traefik.enable=true"
        - "traefik.docker.network=external"
    environment:
      - GOOGLE_CLIENT_ID_FILE=/run/secrets/GOOGLE_CLIENT_ID
      - GOOGLE_CLIENT_SECRET_FILE=/run/secrets/GOOGLE_SECRET
      - NODE_ENV=production
      - SLACK_SECRET_FILE=/run/secrets/SLACK_SECRET
      - PG_ENV_POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
      - REDIS_PORT_6379_TCP_ADDR=redis
      - DB_HOST_OVERRIDE=postgres
    secrets:
      - GOOGLE_CLIENT_ID
      - GOOGLE_SECRET
      - SLACK_SECRET
      - postgres_password
    networks:
      - external
      - old

networks:
  external:
    external: true
  old:

secrets:
  postgres_password:
    external: true
  GOOGLE_CLIENT_ID:
    external: true
  GOOGLE_SECRET:
    external: true
  SLACK_SECRET:
    external: true
