#!/bin/bash

set -e

for secret in "postgres_password" "GOOGLE_CLIENT_ID" "GOOGLE_SECRET" "SLACK_SECRET" "SLACK_CLIENT_ID" "SLACK_CLIENT_SECRET" "SLACK_SLASH_TOKEN" "MAILGUN_DOMAIN" "MAILGUN_SECRET";
do
    if [[ $(docker secret ls | grep $secret) ]];
    then
        continue;
    else
        echo "Need to Set $secret";
        read input;
        echo "$input" | docker secret create $secret -;
    fi;
done;

echo "Secrets Ok";

docker stack deploy --compose-file=docker-compose.database.yml db

docker stack deploy --compose-file=docker-compose.onerepo.yml sse

docker stack deploy --compose-file=docker-compose.alumni.yml alumni

docker stack deploy --compose-file=docker-compose.slackbot.yml slackbot
