#!/bin/bash

set -e

for secret in "postgres_password" "GOOGLE_CLIENT_ID" "GOOGLE_SECRET" "SLACK_SECRET" "GOOGLE_API_KEY" "MENTOR_GOOGLE_CALENDAR";
do
    if [[ $(docker secret ls | grep $secret) ]];
    then
        continue;
    else
        echo "Need to set $secret";
        read input;
        echo "$input" | docker secret create $secret -;
    fi;
done;

echo "Secrets ok";

export TAG=latest
export TAG_API=latest
export HOST=sse.rit.edu

docker stack deploy -c docker-compose.onerepo.yml sse;
