version: '3.1'

services:
  web:
    image: ritsse/onerepo:latest
    # No longer using caddy's cert fetching, so just run on port 80 without it.
    networks:
      - external
    deploy:
     replicas: 1
     labels:
       - "traefik.backend=sse"
       - "traefik.frontend.rule=Host:sse.rit.edu"
       - "traefik.port=80"
       - "traefik.enable=true"
       - "traefik.weight=0"
       - "traefik.docker.network=external"
       - "traefik.backend.loadbalancer.sticky=true"
       - "traefik.backend.loadbalancer.swarm=true"
  # API, running on devlop for now
  api_v2:
    image: ritsse/node-api:latest
    deploy:
      replicas: 1
      labels:
        - "traefik.backend=api_v2"
        - "traefik.frontend.rule=Host:sse.rit.edu;PathPrefix:/api/v2"
        - "traefik.port=3000"
        - "traefik.enable=true"
        - "traefik.docker.network=external"
        - "traefik.backend.loadbalancer.swarm=true"
      resources:
        limits:
          cpus: '0.25'
          memory: 512M
    environment:
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
      - GOOGLE_CLIENT_SECRET_FILE=/run/secrets/GOOGLE_SECRET
      - GOOGLE_CLIENT_ID_FILE=/run/secrets/GOOGLE_CLIENT_ID
      - MAILGUN_SECRET_FILE=/run/secrets/MAILGUN_SECRET
      - MAILGUN_DOMAIN_FILE=/run/secrets/MAILGUN_DOMAIN
      - SLACK_SECRET_FILE=/run/secrets/SLACK_SECRET
      - DB_HOST_OVERRIDE=postgres
      - NODE_ENV=production
    secrets:
      - MAILGUN_SECRET
      - MAILGUN_DOMAIN
      - GOOGLE_CLIENT_ID
      - GOOGLE_SECRET
      - SLACK_SECRET
      - postgres_password
    networks:
      - external
      - internal
  # Just using the production one because A/B testing will be awful
  # will be disabled
  go:
    image: "ritsse/go:dev"
    environment:
      - 'API=http://api_v2:3000'
    networks:
      - external
      - internal
    deploy:
      replicas: 1
      labels:
        - "traefik.backend=go"
        - "traefik.frontend.rule=Host:sse.rit.edu;Path:/go/{link}"
        - "traefik.port=8000"
        - "traefik.enable=true"
        - "traefik.docker.network=external"
        - "traefik.backend.loadbalancer.swarm=true"
networks:
  external:
    external: true
  internal:
    external: true
# All secrets are external until secrets matures a bit more and services can
# provide them
secrets:
  MAILGUN_SECRET:
    external: true
  MAILGUN_DOMAIN:
    external: true
  postgres_password:
    external: true
  GOOGLE_CLIENT_ID:
    external: true
  GOOGLE_SECRET:
    external: true
  SLACK_SECRET:
    external: true
