version: "3.1"

services:
  physics:
    image: ritsse/physics:latest
    networks:
      - external
    deploy:
      replicas: 1
      labels:
        - "traefik.backend=allen"
        - "traefik.frontend.rule=Host:allendoesphysics.com"
        - "traefik.port=3000"
        - "traefik.enable=true"
        - "traefik.weight=0"
        - "traefik.docker.network=external"
        - "traefik.backend.loadbalancer.swarm=true"
        - "traefik.backend.loadbalancer.sticky=true"
      resources:
        limits:
          cpus: '0.25'
          memory: 512M

networks:
  external:
    external: true
